<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>CSMic.StandardLibrary</RootNamespace>
    <AssemblyName>CSMic.StandardLibrary</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Functions\hyperbolic\**" />
    <EmbeddedResource Remove="Functions\hyperbolic\**" />
    <None Remove="Functions\hyperbolic\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\CSMic.Core.csproj" />
  </ItemGroup>

</Project>
