<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<RootNamespace>CSMic.StandardLibrary</RootNamespace>
		<AssemblyName>CSMic.StandardLibrary</AssemblyName>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>2.1.0</Version>
		<PackageId>CSMic.StandardLibrary</PackageId>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Core\CSMic.Core.csproj" />
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<Import Project="NuGetPublish.targets" Condition="Exists('NuGetPublish.targets')" />


</Project>
