<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\core\core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="functions\hyperbolic\" />
  </ItemGroup>

</Project>
