<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<RootNamespace>CSMic</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<AssemblyName>CSMic.Core</AssemblyName>
		<Version>2.0.0</Version>
		<PackageId>CSMic</PackageId>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
		<Exec Command="dotnet tool run coco -namespace CSMic.Interpreter -frames $(ProjectDir)cocor $(ProjectDir)cocor/Interpreter.atg" />
	</Target>

	<Import Project="NuGetPublish.targets" Condition="Exists('NuGetPublish.targets')" />

</Project>
