<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<RootNamespace>CSMic</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<AssemblyName>CSMic.Core</AssemblyName>
		<Version>2.0.1</Version>
		<PackageId>CSMic</PackageId>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
		<Compile Remove="cocor/Parser.cs;cocor/Scanner.cs" />
		<Compile Include="cocor/Parser.cs;cocor/Scanner.cs" />
	</ItemGroup>

	<Target Name="GenerateInterpreter" BeforeTargets="CoreCompile">
		<Exec Command="dotnet tool run coco -namespace CSMic.Interpreter -frames $(ProjectDir)cocor $(ProjectDir)cocor/Interpreter.atg" />
	</Target>

	<Import Project="NuGetPublish.targets" Condition="Exists('NuGetPublish.targets')" />

</Project>
