<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<RootNamespace>CSMic</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<AssemblyName>CSMic.Core</AssemblyName>
		<Version>2.0.0-beta-01</Version>
		<PackageId>CSMic</PackageId>
	</PropertyGroup>

	<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
		<Exec Command="dotnet tool run coco -namespace CSMic.Interpreter -frames $(ProjectDir)CocoR $(ProjectDir)CocoR/Interpreter.atg" />
	</Target>

	<Import Project="NuGetPublish.targets" Condition="Exists('NuGetPublish.targets')" />

</Project>
